### ISSUE TITLE
commonjs export is not working in 0.1.1

### ISSUE THREAD

**Issue by rokoroku** [zsajjad/react-facebook-pixel#10]
```js
const ReactPixel =  require('react-facebook-pixel');
ReactPixel.init('yourPixelIdGoesHere');
```
above code causes `Uncaught TypeError: ReactPixel.init is not a function`

Rather, we have to use `default` export now.
```js
const ReactPixel =  require('react-facebook-pixel').default;
ReactPixel.init('yourPixelIdGoesHere');
```

**Comment by bf** [comment]
There is a babel / webpack plugin which changes this for you. I think it is either           "add-module-exports" or           "transform-es2015-modules-commonjs".

**Comment by zsajjad** [comment]
Hopefully, @bf's solution fixes this

**Comment by rokoroku** [comment]
Seriously? then you'd better change below description in the README.md.

![2018-10-12 12 46 19](https://user-images.githubusercontent.com/5208632/46846959-f33bf880-ce1c-11e8-8290-b5540b5fceb8.png)
